-- SQL Commands to create PlayWin6 database tables
-- Run these commands in your MySQL database

-- Create playwin6_game_sessions table
CREATE TABLE `playwin6_game_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `game_id` varchar(255) NOT NULL COMMENT 'PlayWin6 game identifier',
  `provider` varchar(255) NOT NULL COMMENT 'Game provider (e.g., JiliGaming, PragmaticPlay)',
  `game_type` varchar(255) NOT NULL COMMENT 'Type of game (Slot Game, Live Casino, etc.)',
  `launch_token` varchar(255) NOT NULL COMMENT 'Unique token for this game session launch',
  `session_token` varchar(255) DEFAULT NULL COMMENT 'Token generated by PlayWin6 for current game session',
  `player_username` varchar(255) NOT NULL COMMENT 'Player username for PlayWin6',
  `currency` varchar(10) NOT NULL DEFAULT 'INR' COMMENT 'Game currency',
  `language` varchar(10) NOT NULL DEFAULT 'en' COMMENT 'Game language',
  `platform` enum('mobile','desktop') NOT NULL DEFAULT 'desktop',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address where session was created',
  `status` enum('active','ended','expired','error') NOT NULL DEFAULT 'active',
  `game_url` text DEFAULT NULL COMMENT 'Full game launch URL',
  `provider_url` text DEFAULT NULL COMMENT 'Provider game URL',
  `metadata` json DEFAULT NULL COMMENT 'Additional game metadata',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `launch_token` (`launch_token`),
  KEY `user_id` (`user_id`),
  KEY `session_token` (`session_token`),
  KEY `status` (`status`),
  KEY `game_id` (`game_id`),
  KEY `provider` (`provider`),
  KEY `created_at` (`created_at`),
  KEY `idx_user_game_active` (`user_id`,`game_id`,`status`),
  KEY `idx_provider_status` (`provider`,`status`),
  CONSTRAINT `playwin6_game_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='PlayWin6 game sessions';

-- Create playwin6_transactions table
CREATE TABLE `playwin6_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `session_id` int(11) NOT NULL,
  `type` enum('bet','win','rollback','balance') NOT NULL COMMENT 'Type of transaction',
  `amount` decimal(15,2) NOT NULL COMMENT 'Transaction amount',
  `currency` varchar(10) NOT NULL DEFAULT 'INR' COMMENT 'Transaction currency',
  `provider` varchar(255) NOT NULL COMMENT 'Game provider (e.g., JiliGaming, PragmaticPlay)',
  `game_id` varchar(255) NOT NULL COMMENT 'Game identifier',
  `game_uid` varchar(255) DEFAULT NULL COMMENT 'Game unique identifier from PlayWin6',
  `provider_tx_id` varchar(255) NOT NULL COMMENT 'Transaction ID from PlayWin6',
  `operator_tx_id` varchar(255) NOT NULL COMMENT 'Our internal transaction ID',
  `action` varchar(255) NOT NULL COMMENT 'Action type (bet, win, rollback, balance)',
  `action_id` varchar(255) DEFAULT NULL COMMENT 'Action identifier from game',
  `old_balance` decimal(15,2) NOT NULL COMMENT 'Balance before transaction',
  `new_balance` decimal(15,2) NOT NULL COMMENT 'Balance after transaction',
  `wallet_amount` decimal(15,2) DEFAULT NULL COMMENT 'Wallet amount from callback',
  `status` enum('pending','completed','failed','rolled_back') NOT NULL DEFAULT 'pending',
  `rollback_provider_tx_id` varchar(255) DEFAULT NULL COMMENT 'Reference to original transaction for rollbacks',
  `platform` enum('mobile','desktop') DEFAULT NULL COMMENT 'Platform where transaction occurred',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address where transaction occurred',
  `callback_data` json DEFAULT NULL COMMENT 'Raw callback data from PlayWin6',
  `encrypted_payload` text DEFAULT NULL COMMENT 'Encrypted payload from PlayWin6',
  `timestamp` bigint(20) DEFAULT NULL COMMENT 'Timestamp from PlayWin6 callback',
  `token` varchar(255) DEFAULT NULL COMMENT 'Token from PlayWin6 callback',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `provider_tx_id` (`provider_tx_id`),
  UNIQUE KEY `operator_tx_id` (`operator_tx_id`),
  KEY `user_id` (`user_id`),
  KEY `session_id` (`session_id`),
  KEY `type` (`type`),
  KEY `status` (`status`),
  KEY `game_uid` (`game_uid`),
  KEY `created_at` (`created_at`),
  KEY `idx_rollback_provider_tx` (`rollback_provider_tx_id`),
  KEY `idx_session_type_status` (`session_id`,`type`,`status`),
  KEY `idx_game_uid_provider` (`game_uid`,`provider`),
  CONSTRAINT `playwin6_transactions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `playwin6_transactions_ibfk_2` FOREIGN KEY (`session_id`) REFERENCES `playwin6_game_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='PlayWin6 transactions';

-- Create indexes for better performance
-- Note: Some indexes are already created in the table definitions above

-- Additional composite indexes for common query patterns
CREATE INDEX `idx_playwin6_user_created` ON `playwin6_transactions` (`user_id`, `created_at`);
CREATE INDEX `idx_playwin6_provider_type` ON `playwin6_transactions` (`provider`, `type`);
CREATE INDEX `idx_playwin6_status_created` ON `playwin6_transactions` (`status`, `created_at`);

-- Index for session queries
CREATE INDEX `idx_playwin6_session_created` ON `playwin6_game_sessions` (`session_token`, `created_at`);

-- Index for callback processing
CREATE INDEX `idx_playwin6_callback_timestamp` ON `playwin6_transactions` (`timestamp`, `status`);

-- Add comments to tables for documentation
ALTER TABLE `playwin6_game_sessions` COMMENT = 'Stores PlayWin6 game session information including launch tokens, game metadata, and session status';
ALTER TABLE `playwin6_transactions` COMMENT = 'Stores PlayWin6 transaction records including bets, wins, rollbacks, and balance updates';

-- Verify tables were created successfully
SELECT 
    TABLE_NAME,
    TABLE_ROWS,
    TABLE_COMMENT
FROM 
    INFORMATION_SCHEMA.TABLES 
WHERE 
    TABLE_SCHEMA = DATABASE() 
    AND TABLE_NAME IN ('playwin6_game_sessions', 'playwin6_transactions');

-- Show table structure for verification
DESCRIBE `playwin6_game_sessions`;
DESCRIBE `playwin6_transactions`; 