-- Create spribe_game_sessions table
CREATE TABLE IF NOT EXISTS `spribe_game_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `game_id` varchar(255) NOT NULL,
  `provider` varchar(50) NOT NULL DEFAULT 'spribe',
  `launch_token` varchar(255) NOT NULL,
  `session_token` varchar(255) NOT NULL,
  `currency` varchar(10) NOT NULL DEFAULT 'EUR',
  `platform` varchar(50) DEFAULT 'desktop',
  `ip_address` varchar(45) DEFAULT NULL,
  `status` enum('active','ended','expired','error') NOT NULL DEFAULT 'active',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `launch_token` (`launch_token`),
  KEY `user_id` (`user_id`),
  KEY `session_token` (`session_token`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`),
  CONSTRAINT `spribe_game_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Create spribe_transactions table
CREATE TABLE IF NOT EXISTS `spribe_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `session_id` int NOT NULL,
  `type` enum('bet','win','rollback') NOT NULL,
  `amount` bigint NOT NULL,
  `currency` varchar(10) NOT NULL DEFAULT 'EUR',
  `provider` varchar(50) NOT NULL DEFAULT 'spribe',
  `game_id` varchar(255) NOT NULL,
  `provider_tx_id` varchar(255) NOT NULL,
  `operator_tx_id` varchar(255) NOT NULL,
  `action` varchar(50) NOT NULL,
  `action_id` varchar(255) DEFAULT NULL,
  `old_balance` bigint NOT NULL,
  `new_balance` bigint NOT NULL,
  `status` enum('pending','completed','failed','rolled_back') NOT NULL DEFAULT 'pending',
  `withdraw_provider_tx_id` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `provider_tx_id` (`provider_tx_id`),
  UNIQUE KEY `operator_tx_id` (`operator_tx_id`),
  KEY `user_id` (`user_id`),
  KEY `session_id` (`session_id`),
  KEY `type` (`type`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`),
  CONSTRAINT `spribe_transactions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`),
  CONSTRAINT `spribe_transactions_ibfk_2` FOREIGN KEY (`session_id`) REFERENCES `spribe_game_sessions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 