// models/PlayWin6GameSession.js - PlayWin6 Game Session Model
const { Model, DataTypes } = require('sequelize');

class PlayWin6GameSession extends Model {
    static init(sequelize) {
        return super.init({
            id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            user_id: {
                type: DataTypes.INTEGER,
                allowNull: false,
                references: {
                    model: 'users',
                    key: 'user_id'
                }
            },
            game_id: {
                type: DataTypes.STRING,
                allowNull: false,
                comment: 'PlayWin6 game identifier'
            },
            provider: {
                type: DataTypes.STRING,
                allowNull: false,
                comment: 'Game provider (e.g., JiliGaming, PragmaticPlay)'
            },
            game_type: {
                type: DataTypes.STRING,
                allowNull: false,
                comment: 'Type of game (Slot Game, Live Casino, etc.)'
            },
            launch_token: {
                type: DataTypes.STRING,
                allowNull: false,
                unique: true,
                comment: 'Unique token for this game session launch'
            },
            session_token: {
                type: DataTypes.STRING,
                allowNull: true,
                comment: 'Token generated by PlayWin6 for current game session'
            },
            player_username: {
                type: DataTypes.STRING,
                allowNull: false,
                comment: 'Player username for PlayWin6'
            },
            currency: {
                type: DataTypes.STRING,
                allowNull: false,
                defaultValue: 'INR',
                comment: 'Game currency'
            },
            language: {
                type: DataTypes.STRING,
                allowNull: false,
                defaultValue: 'en',
                comment: 'Game language'
            },
            platform: {
                type: DataTypes.ENUM('mobile', 'desktop'),
                allowNull: false,
                defaultValue: 'desktop'
            },
            ip_address: {
                type: DataTypes.STRING,
                allowNull: true,
                comment: 'IP address where session was created'
            },
            status: {
                type: DataTypes.ENUM('active', 'ended', 'expired', 'error'),
                allowNull: false,
                defaultValue: 'active'
            },
            game_url: {
                type: DataTypes.TEXT,
                allowNull: true,
                comment: 'Full game launch URL'
            },
            provider_url: {
                type: DataTypes.TEXT,
                allowNull: true,
                comment: 'Provider game URL'
            },
            metadata: {
                type: DataTypes.JSON,
                allowNull: true,
                comment: 'Additional game metadata'
            },
            started_at: {
                type: DataTypes.DATE,
                allowNull: false,
                defaultValue: DataTypes.NOW
            },
            ended_at: {
                type: DataTypes.DATE,
                allowNull: true
            },
            created_at: {
                type: DataTypes.DATE,
                defaultValue: DataTypes.NOW
            },
            updated_at: {
                type: DataTypes.DATE,
                defaultValue: DataTypes.NOW
            }
        }, {
            sequelize,
            modelName: 'PlayWin6GameSession',
            tableName: 'playwin6_game_sessions',
            timestamps: true,
            createdAt: 'created_at',
            updatedAt: 'updated_at',
            indexes: [
                {
                    fields: ['user_id']
                },
                {
                    fields: ['launch_token']
                },
                {
                    fields: ['session_token']
                },
                {
                    fields: ['status']
                },
                {
                    fields: ['game_id']
                },
                {
                    fields: ['provider']
                },
                {
                    fields: ['created_at']
                },
                {
                    // Composite index for finding active sessions
                    name: 'idx_user_game_active',
                    fields: ['user_id', 'game_id', 'status']
                },
                {
                    // Composite index for provider sessions
                    name: 'idx_provider_status',
                    fields: ['provider', 'status']
                }
            ]
        });
    }

    static associate(models) {
        // User association
        if (models.User) {
            this.belongsTo(models.User, {
                foreignKey: 'user_id',
                as: 'user'
            });
        }

        // Association with PlayWin6Transaction
        if (models.PlayWin6Transaction) {
            this.hasMany(models.PlayWin6Transaction, {
                foreignKey: 'session_id',
                as: 'transactions'
            });
        }
    }

    // Instance methods for session management
    
    // Check if session is still valid
    isValid() {
        const now = new Date();
        const sessionAge = now - new Date(this.started_at);
        const maxAge = 4 * 60 * 60 * 1000; // 4 hours
        
        return this.status === 'active' && sessionAge < maxAge;
    }

    // Get session duration in seconds
    getDuration() {
        const endTime = this.ended_at || new Date();
        const startTime = new Date(this.started_at);
        return Math.floor((endTime - startTime) / 1000);
    }

    // Mark session as expired
    async markAsExpired() {
        await this.update({
            status: 'expired',
            ended_at: new Date()
        });
    }

    // Mark session as ended
    async markAsEnded() {
        await this.update({
            status: 'ended',
            ended_at: new Date()
        });
    }

    // Mark session as error
    async markAsError() {
        await this.update({
            status: 'error',
            ended_at: new Date()
        });
    }

    // Get session summary
    getSummary() {
        return {
            id: this.id,
            game_id: this.game_id,
            provider: this.provider,
            game_type: this.game_type,
            status: this.status,
            currency: this.currency,
            started_at: this.started_at,
            ended_at: this.ended_at,
            duration: this.getDuration(),
            is_valid: this.isValid()
        };
    }
}

module.exports = PlayWin6GameSession; 